import Head from 'next/head';
import Layout from '@/components/Layout';
import Image from 'next/image';
import profilePic from '../../public/images/profile/developer-pic-1.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import LightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg';
import TransitionEffect from '@/components/TransitionEffect';

export default function Home() {
  return (
    <>
      <Head>
        <title>Jay | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-[#1b1b1b] w-full min-h-screen dark:text-[#f5f5f5]">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex flex-col lg:flex-row items-center justify-between w-full">
            {/* IMAGE */}
            <div className="w-full lg:w-1/2 mb-8 lg:mb-0">
              <Image
                src={profilePic}
                alt="Jay"
                className="w-full h-auto rounded-lg"
                priority
                sizes="(max-width: 768px) 100vw,
                       (max-width: 1200px) 50vw,
                       50vw"
              />
            </div>

            {/* TEXT CONTENT */}
            <div className="w-full lg:w-1/2 flex flex-col items-center lg:items-start text-center lg:text-left">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-5xl sm:!text-4xl md:!text-5xl lg:!text-6xl xl:!text-6xl"
              />
              <p className="my-4 text-base sm:text-sm md:text-base font-medium max-w-xl">
                As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>

              <div className="flex flex-col sm:flex-row items-center mt-4 gap-4">
                <Link
                  href="/Jay Amper(Resume).pdf"
                  target="_blank"
                  download={true}
                  className="flex items-center bg-[#1b1b1b] text-[#f5f5f5] p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-[#f5f5f5] hover:text-[#1b1b1b]
                  border-2 border-solid border-transparent hover:border-[#1b1b1b]
                  dark:bg-[#f5f5f5] dark:text-[#1b1b1b] hover:dark:bg-[#1b1b1b] hover:dark:text-[#f5f5f5]
                  hover:dark:border-[#f5f5f5]"
                >
                  Resume <LinkArrow className="w-6 ml-2" />
                </Link>
                <Link
                  href="mailto:jayamper712@gmail.com"
                  target="_blank"
                  className="text-lg font-medium capitalize text-[#1b1b1b] underline dark:text-[#f5f5f5]"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />

        <div className="absolute right-4 bottom-4 w-16 md:w-24">
          <Image src={LightBulb} alt="Lightbulb" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
export async function getStaticProps() {
  return {
    props: {}, // no dynamic props yet
  };
}